# Generated by Django 5.2 on 2025-04-13 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wellnest', '0002_videosuggestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoSuggestion',
        ),
    ]
